name: chat_gpt
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_inappwebview: ^5.7.2+3
  flutter_bloc: ^8.1.1
  http: ^0.13.5
  get_it: ^7.2.0
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.8
  equatable: ^2.0.5
  avatar_glow: ^2.0.2
  text_to_speech: ^0.2.3
  speech_to_text: ^6.1.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/icons/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

 